### ISSUE TITLE
blDeleteResiduePDB function not found

### ISSUE THREAD

**Issue by edfajardo** [ACRMGroup/bioptools#4]
Hi.  Trying to instal bioptools from source.  Installed bioplib as directed with ./makemake.pl -bioplib 
Installation failed in compilation during the make step with the following messages: 

pdbpatchnumbering.c: In function ‘ApplyPatches’:
pdbpatchnumbering.c:506: warning: implicit declaration of function ‘ blDeleteResiduePDB’
pdbpatchnumbering.c:506: warning: assignment makes pointer from integer without a cast
/tmp/ccE0awis.o: In function `ApplyPatches':
pdbpatchnumbering.c:(.text+0x223): undefined reference to `blDeleteResiduePDB'
collect2: ld returned 1 exit status
make: *** [pdbpatchnumbering] Error 1

Looks like blDeleteResiduePDB should be declared in pdb.h of bioplib, but it is not there.  

We are running gcc 4.4.7 on a CentOS 6.9, kernel 2.6.32 machine. 

Thank you.

**Comment by AndrewCRMartin** [comment]
Ah - i suspect it needs a newer version of bioplib and I've forgotten to
update the install script to pull down a newer version. I'm away at the
moment but will sort it out when I get back.

In the mean time, you can download and install the latest bioplib
separately and then install bioptools without the -bioplib flag.

Best wishes
Andrew

**Comment by edfajardo** [comment]
That worked well.  Thanks for the quick reply. 

Eduardo

**Comment by AndrewCRMartin** [comment]
The install of the previous version worked correctly if you use the last official release, but the latest version (rather than release) on GitHub needed a later version of BiopLib.
There is now a new official release of BiopTools that uses the latest BiopLib
